apiVersion: v1
kind: PersistentVolume
metadata:
  name: snapshots-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain     
  nfs:
    server: 10.0.70.46   #Ec2 private IP used as NFS server and for tailscale exitnode
    path: /mnt/snapshots
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshots-pvc
  namespace: wazuh    
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi