# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Wazuh master StatefulSet

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager-master
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-manager
      node-type: master
  serviceName: wazuh-cluster
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: wazuh-manager
        node-type: master
      name: wazuh-manager-master
    spec:
      volumes:  
        - name: custom-misp-script  #########START MY CONFIG##############
          configMap:
            name: custom-misp
        - name: custom-iris-script    
          configMap:
            name: custom-iris    
        - name: entrypoint-sh-configmap
          configMap:
            name: entrypointsh   
            defaultMode: 0755  # Para que sea ejecutable                                                   
        - name: sentinelone-rules 
          configMap:
            name: sentinelone-rules-configmap 
        - name: sentinelone-decoders
          configMap:
            name: sentinelone-decoders-configmap  
        - name: misp-rules
          configMap:
            name: misp-rules-configmap
        - name: local-rules
          configMap:
            name: local-rules-configmap
        - name: wazuh-template-json
          configMap:
            name: wazuh-template-json-configmap                  ########ENDS MY CONFIG######               
        - name: config
          configMap:
            name: wazuh-conf
        - name: filebeat-certs
          secret:
            secretName: indexer-certs
        - name: wazuh-authd-pass
          secret:
            secretName: wazuh-authd-pass
      securityContext:
        fsGroup: 101                                          
      containers:
        - name: wazuh-manager
          image: 'wazuh/wazuh-manager:4.12.0'
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
          securityContext:
            capabilities:
              add: ["SYS_CHROOT"]
          volumeMounts:
            - name: config   #########START MY CONFIG###############
              mountPath: /etc/filebeat/filebeat.yml 
              subPath: filebeat.yml
            # - name: custom-iris-script
            #   mountPath: /wazuh-config-mount/integrations/custom-wazuh_iris.py
            #   subPath: custom-wazuh_iris.py
            # - name: entrypoint-sh-configmap
            #   mountPath: /usr/local/bin/entrypoint.sh
            #   subPath: entrypoint.sh
            # - name: custom-misp-script
            #   mountPath: /wazuh-config-mount/integrations/custom-misp.py
            #   subPath: custom-misp.py
            #   readOnly: true                                                                  
            - name: sentinelone-rules
              mountPath: /var/ossec/etc/rules/sentinelone_rules.xml
              subPath: sentinelone_rules.xml
              readOnly: true
            - name: sentinelone-decoders
              mountPath: /var/ossec/etc/decoders/sentinelone_decoders.xml
              subPath: sentinelone_decoders.xml
              readOnly: true 
            - name: misp-rules
              mountPath: /var/ossec/etc/rules/misp-rules.xml
              subPath: misp_rules.xml 
              readOnly: true
            - name: local-rules
              mountPath: /var/ossec/etc/rules/local_rules.xml
              subPath: local_rules.xml               
              readOnly: true
            - name: wazuh-template-json
              mountPath: /etc/filebeat/wazuh-template.json
              subPath: wazuh-template.json               
              readOnly: true                      #######ENDS MY CONFIG###############                       
            - name: config
              mountPath: /wazuh-config-mount/etc/ossec.conf
              subPath: master.conf
              readOnly: true
            - name: filebeat-certs
              mountPath: /etc/ssl/root-ca.pem
              readOnly: true
              subPath: root-ca.pem
            - name: filebeat-certs
              mountPath: /etc/ssl/filebeat.pem
              subPath: filebeat.pem
              readOnly: true
            - name: filebeat-certs
              mountPath: /etc/ssl/filebeat.key
              subPath: filebeat-key.pem
              readOnly: true
            - name: wazuh-authd-pass
              mountPath: /wazuh-config-mount/etc/authd.pass
              subPath: authd.pass
              readOnly: true
            - name: wazuh-manager-master
              mountPath: /var/ossec/api/configuration
              subPath: wazuh/var/ossec/api/configuration
            - name: wazuh-manager-master
              mountPath: /var/ossec/etc
              subPath: wazuh/var/ossec/etc
            - name: wazuh-manager-master
              mountPath: /var/ossec/logs
              subPath: wazuh/var/ossec/logs
            - name: wazuh-manager-master
              mountPath: /var/ossec/queue
              subPath: wazuh/var/ossec/queue
            - name: wazuh-manager-master
              mountPath: /var/ossec/var/multigroups
              subPath: wazuh/var/ossec/var/multigroups
            - name: wazuh-manager-master
              mountPath: /var/ossec/integrations
              subPath: wazuh/var/ossec/integrations
            - name: wazuh-manager-master
              mountPath: /var/ossec/active-response/bin
              subPath: wazuh/var/ossec/active-response/bin
            - name: wazuh-manager-master
              mountPath: /var/ossec/agentless
              subPath: wazuh/var/ossec/agentless
            - name: wazuh-manager-master
              mountPath: /var/ossec/wodles
              subPath: wazuh/var/ossec/wodles
            - name: wazuh-manager-master
              mountPath: /etc/filebeat
              subPath: filebeat/etc/filebeat
            - name: wazuh-manager-master
              mountPath: /var/lib/filebeat
              subPath: filebeat/var/lib/filebeat
          # lifecycle:
          #   postStart:
          #     exec:
          #       command: ["/bin/bash", "-c", "/usr/local/bin/entrypoint.sh"]              
          ports:
            - containerPort: 1515
              name: registration
            - containerPort: 1516
              name: cluster
            - containerPort: 55000
              name: api
            - containerPort: 514
              name: syslog-events               
          env:
            - name: INDEXER_URL
              value: 'https://indexer:9200'
            - name: INDEXER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: indexer-cred
                  key: username
            - name: INDEXER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: indexer-cred
                  key: password
            - name: M365_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: m365-cred-secret
                  key: TENANT_ID
            - name: M365_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: m365-cred-secret
                  key: CLIENT_ID
            - name: M365_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: m365-cred-secret
                  key: CLIENT_SECRET                    
            - name: FILEBEAT_SSL_VERIFICATION_MODE
              value: 'full'
            - name: SSL_CERTIFICATE_AUTHORITIES
              value: /etc/ssl/root-ca.pem
            - name: SSL_CERTIFICATE
              value: /etc/ssl/filebeat.pem
            - name: SSL_KEY
              value: /etc/ssl/filebeat.key
            - name: API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wazuh-api-cred
                  key: username
            - name: API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wazuh-api-cred
                  key: password
            - name: WAZUH_CLUSTER_KEY
              valueFrom:
                secretKeyRef:
                  name: wazuh-cluster-key
                  key: key
  volumeClaimTemplates:
    - metadata:
        name: wazuh-manager-master
        namespace: wazuh
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: wazuh-storage
        resources:
          requests:
            storage: 500Mi
