# Wazuh - Filebeat configuration file
filebeat.modules:
  - module: wazuh
    alerts:
      enabled: true
    archives:
      enabled: true

setup.template.json.enabled: true
setup.template.overwrite: true
setup.template.json.path: '/etc/filebeat/wazuh-template.json'
setup.template.json.name: 'wazuh'
setup.ilm.enabled: false
output.elasticsearch:
  hosts: ['https://indexer:9200']
  username: 'admin'
  password: 'soeJKJg4%65.2+-^^'
  ssl.verification_mode: 'full'
  ssl.certificate_authorities: ['/etc/ssl/root-ca.pem']
  ssl.certificate: '/etc/ssl/filebeat.pem'
  ssl.key: '/etc/ssl/filebeat.key'

logging.metrics.enabled: false

seccomp:
  default_action: allow
  syscalls:
  - action: allow
    names:
    - rseq

# Procesadores para modificar los eventos antes de enviarlos a Elasticsearch
# processors:
#   - convert:
#       fields:
#         - {from: "data.data", to: "data.data", type: "string"}
#       ignore_missing: true
#       fail_on_error: false

#   - rename:
#       fields:
#         - from: "data.data"
#           to: "data.new_field"
#       ignore_missing: true

#   - script:
#       lang: painless
#       source: >
#         if (ctx.data?.new_field != null && ctx.data.new_field instanceof String) {
#           ctx.data.new_field = ["value": ctx.data.new_field];
#         }


#   - convert:
#       fields:
#         - field: "data.new_field"
#           type: auto
#       ignore_missing: true
#       ignore_failure: true

#   - set:
#       field: "data.aws.region"
#       value: "{{data.aws.awsRegion}}"
#       override: false
#       ignore_failure: true
#       ignore_empty_value: true