apiVersion: v1
kind: ConfigMap
metadata:
  name: syslog-ng-install-script
  namespace: wazuh-dev
data:
  syslog-install.sh: |
    #!/bin/bash
    set -e
    curl -o /etc/yum.repos.d/czanik-syslog-ng.repo \
    https://copr.fedorainfracloud.org/coprs/czanik/syslog-ng-amazon23/repo/amazonlinux-2023/czanik-syslog-ng-amazon23-amazonlinux-2023.repo

    dnf install syslog-ng -y
    syslog-ng -F -p 6514 &